# This github action will build a Python package module from source
---
name: Build Python Package
description: Builds the given package. FOr this, installs the required packages and pass a QA analysis for PEP8 syntaxis. 

author: Marius Crisan
branding:
  icon: package
  color: blue

inputs:
  module-name:
    description: Name of the module to be compiled
    required: true
    type: string

runs:
  # env:
  #   MODULE_PATH: code/${{ inputs.module-name}}
  
  using: composite
  
  steps:
 
  - name: Set environment variable
    id: vars
    run: |
      echo "module_path=code/${{ inputs.module-name}}" >> $GITHUB_OUTPUT
      
  - name: Install module dependencies
    run: |
      if [ -f "${{ steps.vars.outputs.module_path }}/requirements.txt" ]; then pip install -r ${{ steps.vars.outputs.module_path }}/requirements.txt; fi
    shell: bash

  - name: Lint with pylint
    run: |
      pylint --exit-zero --ignore-pattern=".*\.txt,.*\.yaml, .*\.yml" --rcfile=.vscode/.pylintrc ${{ steps.vars.outputs.module_path }}/
    shell: bash

  - name: Build a binary wheel and a source tarball
    run: |
      python3 -m build --sdist --wheel --outdir dist/ ${{ steps.vars.outputs.module_path }}
    shell: bash