# This github action will build a Python package module from source
---
name: Build Python Package
description: Builds the given package. For this, installs the required packages and pass a QA analysis for PEP8 syntaxis.

author: Marius Crisan
branding:
  icon: package
  color: blue

inputs:
  module-name:
    description: Name of the module to be compiled
    required: false
    type: string
  package-name:
    description: Name of the package to be compiled
    required: false
    type: string

runs:
  using: composite
  steps:

  - name: Set environment variable
    id: vars
    run: |
      if [ -z ${{ inputs.module-name}} ]
      then
        echo "MODULE_PATH=code" >> $GITHUB_ENV
      else
        echo "MODULE_PATH=code/${{ inputs.module-name }}" >> $GITHUB_ENV
        ]
      fi

      if [ -z $${{ inputs.package-name}} ]
      then
        echo "PACKAGE_NAME=${{ inputs.module-name }}" >> $GITHUB_ENV
      else
        echo "PACKAGE_NAME=${{ inputs.package-name }}" >> $GITHUB_ENV
      fi
    shell: bash

  - name: Install module dependencies
    run: |
      if [ -f "${{ env.MODULE_PATH }}/requirements.txt" ]; then pip install -r ${{ env.MODULE_PATH }}/requirements.txt; fi
    shell: bash

  - name: Lint with pylint
    run: |
      pylint --rcfile=.vscode/.pylintrc ${{ env.MODULE_PATH }}/*
    shell: bash

  - name: Check new version
    id: get-version
    run: |
      python3 ${{ github.action_path }}/get_version.py ${{ env.MODULE_PATH }}
    shell: bash

  - name: Build a binary wheel and a source tarball
    run: |
      python3 -m build --sdist --wheel --outdir dist/ ${{ env.PACKAGE_NAME }}
    shell: bash
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.get-version.outputs.new-version }}
