# This github action will build a Python package module from source
---
name: Build Python Package
description: Builds the given package. For this, installs the required packages and pass a QA analysis for PEP8 syntaxis.

author: Marius Crisan
branding:
  icon: package
  color: blue

inputs:
  module-name:
    description: Name of the module to be compiled
    required: false
    type: string
  package-name:
    description: Name of the package to be compiled
    required: false
    type: string

runs:
  using: composite
  steps:

  - name: Install module dependencies
    run: |
      if [ -f "${{ inputs.module-name }}/requirements.txt" ]; then pip install -r ${{ inputs.module-name }}/requirements.txt; fi
    shell: bash

  - name: Lint with pylint
    run: |
      pylint --rcfile=.vscode/.pylintrc ${{ inputs.module-name }}/*
    shell: bash

  - name: Run tests
    run: |
      pytest ${{ inputs.module-name }}/tests/test*.py
    shell: bash

  - name: Check new version
    id: get-version
    run: |
      python3 ${{ github.action_path }}/get_version.py ${{ inputs.module-name }}
    shell: bash

  - name: Build a binary wheel and a source tarball
    run: |
      python3 -m build --sdist --wheel --outdir dist/ ${{ inputs.module-name }}
    shell: bash
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.get-version.outputs.new-version }}
