# This github action will install Python version and generic dependencies
---
name: Setup Python Base
description: Set environment and install generic used dependencies.
author: Marius Crisan
branding:
  icon: package
  color: purple

inputs:
  python-version:
    description: Python version to be configured
    required: true
    default: '3.9'
    type: string

# outputs:
#   dist:
#     description: The location of the built packages.
#     value: ${{ steps.setter.outputs.dist }}

runs:
  using: composite

  steps:
  - uses: actions/checkout@v3
  
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v3
    with:        
      python-version: ${{ inputs.python-version }}

  - name: Install dependencies
    run: |
      python3 -m pip install --upgrade pip
      python3 -m pip install pylint
      python3 -m pip install build --user # pypa/build
